services:
  - type: web
    name: elder-discord-bot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MODMAIL_CHANNEL_ID
        sync: false
      - key: STAFF_ROLE_ID
        sync: false
      - key: GOOGLE_SHEET_URL
        sync: false
      - key: GOOGLE_SHEET_CSV_URL
        sync: false
      - key: PORT
        value: 10000
